
FAIL XMLHttpRequest: members during network errors (sync) assert_throws: send function "function () { client.send(null); }" threw object "Error: NETWORK_ERR: XMLHttpRequest Exception 101" that is not a DOMException NetworkError: property "code" is equal to 101, expected 19(stack: assert@http://localhost:8800/resources/testharness.js:1738:42
assert_throws@http://localhost:8800/resources/testharness.js:682:23
http://localhost:8800/XMLHttpRequest/xmlhttprequest-network-error-sync.htm:23:22
step@http://localhost:8800/resources/testharness.js:798:30
test@http://localhost:8800/resources/testharness.js:73:22
global code@http://localhost:8800/XMLHttpRequest/xmlhttprequest-network-error-sync.htm:20:11)

