
FAIL Keygenerator ConstraintError when using same id as already generated assert_unreached: unexpected db.error (ConstraintError) Reached unreachable code(stack: assert@http://localhost:8800/resources/testharness.js:1738:42
assert_unreached@http://localhost:8800/resources/testharness.js:692:16
http://localhost:8800/IndexedDB/support.js:50:29
step@http://localhost:8800/resources/testharness.js:798:30
http://localhost:8800/resources/testharness.js:827:40)

