Blocked access to external URL http://www2.localhost:8800/eventsource/resources/cors.py?run=cache-control

Harness Error. harness_status.status = 2 , harness_status.message = null
